/*에러로그 ERROR_LOG*/

SELECT * FROM ERROR_LOG;
SELECT COUNT(*) FROM ERROR_LOG;
commit;

SELECT COUNT(P_NAME) FROM ERROR_LOG;

SELECT DISTINCT P_NAME, COUNT(*) OVER(PARTITION BY E_NAME) as EPTOT FROM ERROR_LOG;
Delete FROM ERROR_LOG WHERE P_NAME = '124';
UPDATE ERROR_LOG SET P_NAME = '여름 반팔D' WHERE LOG_ID = 'L202307241';

DROP TABLE ERROR_LOG;
CREATE TABLE ERROR_LOG (
    LOG_ID VARCHAR2(50) PRIMARY KEY,
    P_CODE VARCHAR2(15) NOT NULL,
    P_NAME VARCHAR2(30),
    E_CODE VARCHAR2(10) NOT NULL,
    E_NAME VARCHAR2(20),
    ERROR_COUNT NUMBER,
    ERROR_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT UC_ERROR UNIQUE (P_CODE, E_CODE)
);

CREATE OR REPLACE TRIGGER TRIGGER_ERROR_LOG
BEFORE INSERT ON ERROR_LOG
FOR EACH ROW
DECLARE
    LOG_COUNT NUMBER;
    LOG_DATE VARCHAR2(20);
BEGIN
    LOG_DATE := TO_CHAR(SYSDATE, 'YYYYMMDD');
    
    SELECT COUNT(*) INTO LOG_COUNT FROM ERROR_LOG WHERE LOG_ID LIKE 'L' || LOG_DATE || '%';
    :NEW.LOG_ID := 'L' || LOG_DATE || TO_CHAR(LOG_COUNT + 1);
END;
/

DROP SEQUENCE ERRORLOG_SEQ;
CREATE SEQUENCE ERRORLOG_SEQ
INCREMENT BY 1
START WITH 21
MINVALUE 20
MAXVALUE 10000
NOCYCLE;

DROP SEQUENCE ERRORLOG_SEQ;
CREATE SEQUENCE ERRORLOG_SEQ
INCREMENT BY 1
START WITH 2
MINVALUE 2
MAXVALUE 10000
NOCYCLE;


-- 1부터 10000까지의 숫자로 반복하여 INSERT 문 실행
BEGIN
   FOR i IN 1..100 LOOP
        INSERT INTO ERROR_LOG (P_CODE, P_NAME, E_CODE, E_NAME, ERROR_COUNT)
        VALUES ('E230718_' || ERRORLOG_SEQ.NEXTVAL, '여름 반팔A', 'E0001', '제품코드', 3);
        INSERT INTO ERROR_LOG (P_CODE, P_NAME, E_CODE, E_NAME, ERROR_COUNT)
        VALUES ('E230701_' || ERRORLOG_SEQ.NEXTVAL, '여름 반팔A', 'E0003', '제품코드', 3);
        INSERT INTO ERROR_LOG (P_CODE, P_NAME, E_CODE, E_NAME, ERROR_COUNT)
        VALUES ('E230702_' || ERRORLOG_SEQ.NEXTVAL, '여름 반팔B', 'E0002', '제품명', 2);
        INSERT INTO ERROR_LOG (P_CODE, P_NAME, E_CODE, E_NAME, ERROR_COUNT)
        VALUES ('E230703_' || ERRORLOG_SEQ.NEXTVAL, '여름 반팔B', 'E0001', '제품명', 3);
        INSERT INTO ERROR_LOG (P_CODE, P_NAME, E_CODE, E_NAME, ERROR_COUNT)
        VALUES ('E230704_' || ERRORLOG_SEQ.NEXTVAL, '여름 반팔B', 'E0000', '제품명', 10);
        INSERT INTO ERROR_LOG (P_CODE, P_NAME, E_CODE, E_NAME, ERROR_COUNT)
        VALUES ('E230705_' || ERRORLOG_SEQ.NEXTVAL, '여름 반팔B', 'E0005', '제품명', 1);
        INSERT INTO ERROR_LOG (P_CODE, P_NAME, E_CODE, E_NAME, ERROR_COUNT)
        VALUES ('E230706' || ERRORLOG_SEQ.NEXTVAL, '여름 원피스B', 'E0000', '제품명', 3);
        INSERT INTO ERROR_LOG (P_CODE, P_NAME, E_CODE, E_NAME, ERROR_COUNT)
        VALUES ('E230707' || ERRORLOG_SEQ.NEXTVAL, '여름 원피스B', 'E0002', '제품명', 8);
        INSERT INTO ERROR_LOG (P_CODE, P_NAME, E_CODE, E_NAME, ERROR_COUNT)
        VALUES ('E230708' || ERRORLOG_SEQ.NEXTVAL, '어린이 반팔B', 'E0002', '제품명', 5);
        INSERT INTO ERROR_LOG (P_CODE, P_NAME, E_CODE, E_NAME, ERROR_COUNT)
        VALUES ('E230709' || ERRORLOG_SEQ.NEXTVAL, '어린이 반바지B', 'E0002', '제품명', 2);
        INSERT INTO ERROR_LOG (P_CODE, P_NAME, E_CODE, E_NAME, ERROR_COUNT)
        VALUES ('E230710' || ERRORLOG_SEQ.NEXTVAL, '여름 반바지B', 'E0001', '제품명', 7);
        INSERT INTO ERROR_LOG (P_CODE, P_NAME, E_CODE, E_NAME, ERROR_COUNT)
        VALUES ('E230711' || ERRORLOG_SEQ.NEXTVAL, '여름 반바지B', 'E0002', '제품명', 1);
   END LOOP;
   COMMIT; -- 변경 내용을 커밋하여 영구적으로 저장
END;
/

INSERT INTO ERROR_LOG (P_CODE, P_NAME, E_CODE, E_NAME, ERROR_COUNT)
VALUES ('P230719_1', '여름 남자 반팔A', 'E0003', '제품코드', 21);

INSERT INTO ERROR_LOG (P_CODE, P_NAME, E_CODE, E_NAME, ERROR_COUNT)
VALUES ('P230701_1', '여름 남자 반팔A', 'E0003', '제품코드', 53);
INSERT INTO ERROR_LOG (P_CODE, P_NAME, E_CODE, E_NAME, ERROR_COUNT)
VALUES ('P230701_2', '여름 남자 반팔B', 'E0002', '제품명', 22);
INSERT INTO ERROR_LOG (P_CODE, P_NAME, E_CODE, E_NAME, ERROR_COUNT)
VALUES ('P230701_3', '여름 여자 반팔B', 'E0001', '제품명', 53);
INSERT INTO ERROR_LOG (P_CODE, P_NAME, E_CODE, E_NAME, ERROR_COUNT)
VALUES ('P230701_4', '여름 여자 반팔B', 'E0000', '제품명', 110);
INSERT INTO ERROR_LOG (P_CODE, P_NAME, E_CODE, E_NAME, ERROR_COUNT)
VALUES ('P230701_4', '여름 여자 반팔B', 'E0005', '제품명', 10);
INSERT INTO ERROR_LOG (P_CODE, P_NAME, E_CODE, E_NAME, ERROR_COUNT)
VALUES ('P230703_2', '여름 여자 원피스B', 'E0000', '제품명', 333);
INSERT INTO ERROR_LOG (P_CODE, P_NAME, E_CODE, E_NAME, ERROR_COUNT)
VALUES ('P230703_2', '여름 여자 원피스B', 'E0002', '제품명', 8);
INSERT INTO ERROR_LOG (P_CODE, P_NAME, E_CODE, E_NAME, ERROR_COUNT)
VALUES ('P230702_6', '어린이 반팔B', 'E0002', '제품명', 150);
INSERT INTO ERROR_LOG (P_CODE, P_NAME, E_CODE, E_NAME, ERROR_COUNT)
VALUES ('P230701_6', '어린이 반바지B', 'E0002', '제품명', 210);
INSERT INTO ERROR_LOG (P_CODE, P_NAME, E_CODE, E_NAME, ERROR_COUNT)
VALUES ('P230702_4', '여름 여자 반바지B', 'E0001', '제품명', 2);
INSERT INTO ERROR_LOG (P_CODE, P_NAME, E_CODE, E_NAME, ERROR_COUNT)
VALUES ('P230702_4', '여름 여자 반바지B', 'E0002', '제품명', 20);
